"""initial migration

Revision ID: 64187aef5ceb
Revises:
Create Date: 2023-10-23 17:27:35.871128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64187aef5ceb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inv_analysis_cups",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("cup_type", sa.String(50), nullable=False),
        sa.Column("quantity", sa.Integer, nullable=False),
        sa.Column("cost", sa.Float, nullable=False)
    )

    op.create_table(
        "customers",
        sa.Column("customer_id", sa.Integer, primary_key=True),
        sa.Column("first_name", sa.String(50), nullable=False),
        sa.Column("last_name", sa.String(50), nullable=False),
        sa.Column("email", sa.String(100), nullable=False),
        sa.Column("credit_card_token", sa.String(16), nullable=False),
    )

    op.create_table(
        "sales",
        sa.Column("sale_id", sa.Integer, primary_key=True),
        sa.Column("customer_id", sa.Integer, sa.ForeignKey('customers.customer_id')),
        sa.Column("sale_date", sa.Date, nullable=False),
        sa.Column("sale_amount", sa.Integer, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inv_analysis_cups")
    op.drop_table("customers")
    op.drop_table("albums")
    # ### end Alembic commands ###
