"""updated join table

Revision ID: 607cf8138f75
Revises: c6bdae6cc888
Create Date: 2023-12-21 01:33:08.583658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607cf8138f75'
down_revision: Union[str, None] = 'c6bdae6cc888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ind_cup_sale', sa.Column('sale_id', sa.Integer(), nullable=False))
    op.drop_constraint('ind_cup_sale_cup_id_fkey', 'ind_cup_sale', type_='foreignkey')
    op.create_foreign_key(None, 'ind_cup_sale', 'inv_analysis_cups', ['cup_id'], ['id'])
    op.create_foreign_key(None, 'ind_cup_sale', 'sales', ['sale_id'], ['sale_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ind_cup_sale', type_='foreignkey')
    op.drop_constraint(None, 'ind_cup_sale', type_='foreignkey')
    op.create_foreign_key('ind_cup_sale_cup_id_fkey', 'ind_cup_sale', 'sales', ['cup_id'], ['sale_id'])
    op.drop_column('ind_cup_sale', 'sale_id')
    # ### end Alembic commands ###
