"""added join table

Revision ID: c6bdae6cc888
Revises: 3d5388a32122
Create Date: 2023-12-20 02:34:51.272028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bdae6cc888'
down_revision: Union[str, None] = '3d5388a32122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ind_cup_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('cup_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cup_id'], ['sales.sale_id'], ),
    sa.ForeignKeyConstraint(['cust_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ind_cup_sale')
    # ### end Alembic commands ###
